### ISSUE TITLE
Hygieia-jira collector throwing ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray

### ISSUE THREAD

**Issue by Shubhamk0503** [Hygieia/hygieia-feature-jira-collector#32]
2020-02-09 19:48:14,276 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Located managed bean 'configurationPropertiesRebinder': registering with JMX server as MBean [org.springframework.cloud.context.properties:name=configurationPropertiesRebinder,context=5e95cb5d,type=ConfigurationPropertiesRebinder]
2020-02-09 19:48:14,552 [main] INFO  com.capitalone.dashboard.Application - Started Application in 45.841 seconds (JVM running for 56.494)
2020-02-09 19:49:00,000 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2020-02-09 19:49:00,089 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=http://10.38.101.208:8080/rest/api/2/issuetype status=200 duration=65
2020-02-09 19:49:00,103 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-02-09 19:49:00,104 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - http://10.38.101.208:8080/
2020-02-09 19:49:00,104 [taskScheduler-1] INFO  c.c.d.collector.CollectorTask - -----------------------------------
2020-02-09 19:49:00,104 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - JIRA Collector is set to work in Board mode
2020-02-09 19:49:00,104 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Hours since last run = 14. Collector is only collecting updated/new issues.
2020-02-09 19:49:00,132 [taskScheduler-1] INFO  c.c.d.collector.FeatureCollectorTask - Collecting 1 of 2 boards.
2020-02-09 19:49:00,454 [taskScheduler-1] INFO  c.c.dashboard.client.RestClient - makeRestCall op=GET url=http://10.38.101.208:8080/rest/agile/1.0/board/31/issue?jql=issueType in ('Epic','Story','Task','Bug') and updatedDate>='2020/01/10 19:49'&fields=id,key,issuetype,status,summary,created,updated,project,issuelinks,assignee,sprint,epic,aggregatetimeoriginalestimate,timeoriginalestimate,customfield_10400,customfield_10200,customfield_10102,customfield_10106&startAt=0 status=200 duration=303
2020-02-09 19:49:00,466 [taskScheduler-1] **ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray**
	at com.capitalone.dashboard.collector.DefaultJiraClient.getSprint(DefaultJiraClient.java:611) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getFeature(DefaultJiraClient.java:534) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultJiraClient.lambda$getFeaturesFromQueryURL$1(DefaultJiraClient.java:407) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_222]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getFeaturesFromQueryURL(DefaultJiraClient.java:393) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.DefaultJiraClient.getIssues(DefaultJiraClient.java:269) ~[jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.lambda$updateStoryInformation$7(FeatureCollectorTask.java:277) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_222]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.updateStoryInformation(FeatureCollectorTask.java:274) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:159) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:48) [jira-feature-collector.jar!/:3.1.2-SNAPSHOT]
	at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-3.1.9.jar!/:3.1.2-SNAPSHOT]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.2.5.RELEASE.jar!/:4.2.5.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]

**Comment by Shubhamk0503** [comment]
Earlier jira collector was working fine but now from past days getting below error 

**ERROR c.c.d.collector.FeatureCollectorTask - Failed to collect jira information
java.lang.ClassCastException: org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray**

@Sbrenthughes  i have ping you over gitter for the same.

Need help for this.

**Comment by Shubhamk0503** [comment]
@rvema

**Comment by mvineza** [comment]
I'm encountering same issue.

**Comment by mvineza** [comment]
I solved this issue. Basically when the collector runs to fetch data from Jira API, it sometimes encounter null values for `custom_fields*` settings which is probably the source of the error message. Try removing those from `application.properties` file and restart the collector.

**Comment by Shubhamk0503** [comment]
# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=27017

# MongoDB replicaset
dbreplicaset=false
#dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2020-01-01T00:00:00.000000
feature.masterStartDate=2020-01-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2020-01-01T00:00:00.000000
feature.collectorItemOnlyUpdate=true

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
#feature.jiraProxyUrl=http://proxy.com
feature.jiraProxyPort=8080
feature.jiraBaseUrl=http://X.X.X.X:8080/
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=c2t1bWFyMjpza3VtYXI=

# OAuth is not fully implemented; please blank-out the OAuth values:

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Epic,Story,Task,Bug

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10200

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10102

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10106

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=customfield_10400

#############################################################################
# In Jira, your instance will have its own Id for the issueTypes.
# You can retrieve the issueType IDs from the following API request:
# https://[your-jira-domain-name]/rest/api/2/issuetype
#############################################################################
feature.jiraStoryIds[0]=10102
feature.jiraStoryIds[1]=10004
feature.jiraStoryIds[2]=10002
feature.jiraStoryIds[3]=10105
feature.jiraStoryIds[4]=10003
feature.jiraStoryIds[5]=10103

#############################################################################
# In Jira, your instance will have its own Id for the Epic
# You can find the value from the following API request:
# https://[your-jira-domain-name]/rest/api/2/issuetype
#############################################################################
feature.jiraEpicId=10002

# Defines how to update features per board. If true then only update based on enabled collectorItems otherwise full update
feature.collectorItemOnlyUpdate=true

#Defines the maximum number of features allow per board. If limit is reach collection will not happen for given board
feature.maxNumberOfFeaturesPerBoard=100

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true


feature.jiraIssueTypeNames=Story 
feature.jiraSprintDataFieldName=customfield_10200
feature.jiraEpicIdFieldName=customfield_10102
feature.jiraStoryPointsFieldName=customfield_10106
feature.jiraTeamFieldName=customfield_10400
#feature.jiraBoardAsTeam=true

#In-built folder housing prepared REST queries (required)
#feature.queryFolder=jiraapi-queries





this is my properties file can you help me on that how to resolve that issue
@mvineza

**Comment by Shubhamk0503** [comment]
@mvineza need help on the same to resolve that

**Comment by mvineza** [comment]
> @mvineza need help on the same to resolve that

@Shubhamk0503 Try first to comment out these lines and restart the collector.

```
feature.jiraSprintDataFieldName=customfield_10200
feature.jiraEpicIdFieldName=customfield_10102
feature.jiraStoryPointsFieldName=customfield_10106
feature.jiraTeamFieldName=customfield_10400
```

Then from then on, try adding one by one and restart collector. But make sure you have the correct value (e.g customfield_XYZ).

Example:
```
1. Comment out the 4 settings above.
2. Restart collector.
3. Check if the "java.lang.ClassCastException" no longer appear on the logs. If all good, proceed to the next step.
4. Add feature.jiraSprintDataFieldName=customfield_10200 settings and restart collector.
5. Check if "java.lang.ClassCastException" still doesn't appear on the logs. If all good, proceed to the next step.
6. and so on..
```

Basically you want to isolate what settings causes the java exception. If you were able to determine what setting it is, double check if the value is correct.

**Comment by Shubhamk0503** [comment]
Thanks alot for the help @mvineza  it help to resolve the issue by comment out that.

**Comment by shubhamk0305** [comment]
Hi @mvineza,


I am facing on issue in jira collector 

# Database Name
dbname=dashboarddb

# Database HostName - default is localhost
dbhost=localhost

# Database Port - default is 27017
dbport=28017

# MongoDB replicaset
dbreplicaset=[false if you are not using MongoDB replicaset]
dbhostport=[host1:port1,host2:port2,host3:port3]

# Database Username - default is blank
dbusername=dashboarduser

# Database Password - default is blank
dbpassword=dbpassword

# Logging File location
logging.file=./logs/jira.log

# PageSize - Expand contract this value depending on Jira implementation's
# default server timeout setting (You will likely receive a SocketTimeoutException)
feature.pageSize=100

# Delta change date that modulates the collector item task
# Occasionally, these values should be modified if database size is a concern
feature.deltaStartDate=2019-03-01T00:00:00.000000
feature.masterStartDate=2019-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2019-03-01T00:00:00.000000

# Chron schedule: S M D M Y [Day of the Week]
feature.cron=0 * * * * *

# ST Query File Details - Required, but DO NOT MODIFY
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic

# JIRA CONNECTION DETAILS:
# Enterprise Proxy - ONLY INCLUDE IF YOU HAVE A PROXY
feature.jiraProxyUrl=http://proxy.com
feature.jiraProxyPort=9000
feature.jiraBaseUrl=http://172.32.31.207:9090
feature.jiraQueryEndpoint=rest/api/2/
# For basic authentication, requires username:password as string in base64
# This command will make this for you:  echo -n username:password | base64

feature.jiraCredentials=aGtib3NzOmthbG1ldWRlZ2E=

# OAuth is not fully implemented; please blank-out the OAuth values:

feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=

#############################################################################
# In Jira, general IssueType IDs are associated to various 'issue'
# attributes. However, there is one attribute which this collector's
# queries rely on that change between different instantiations of Jira.
# Please provide a string name reference to your instance's IssueType for
# the lowest level of Issues (for example, 'user story') specific to your Jira
# instance.  Note:  You can retrieve your instance's IssueType Name
# listings via the following URI:  https://[your-jira-domain-name]/rest/api/2/issuetype/
# Multiple comma-separated values can be specified.
#############################################################################
feature.jiraIssueTypeNames=Story

#############################################################################
# In Jira, your instance will have its own custom field created for 'sprint' or 'timebox' details,
# which includes a list of information.  This field allows you to specify that data field for your
# instance of Jira. Note: You can retrieve your instance's sprint data field name
# via the following URI, and look for a package name com.atlassian.greenhopper.service.sprint.Sprint;
# your custom field name describes the values in this field:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraSprintDataFieldName=customfield_10101

#############################################################################
# In Jira, your instance will have its own custom field created for 'super story' or 'epic' back-end ID,
# which includes a list of information.  This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's epic ID field name via the following URI where your
# queried user story issue has a super issue (for example, epic) tied to it; your custom field name describes the
# epic value you expect to see, and is the only field that does this for a given issue:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraEpicIdFieldName=customfield_10102

#############################################################################
# In Jira, your instance will have its own custom field created for 'story points'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's storypoints ID field name via the following URI where your
# queried user story issue has story points set on it; your custom field name describes the
# story points value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraStoryPointsFieldName=customfield_10106

#############################################################################
# In Jira, your instance will have its own custom field created for 'team'
# This field allows you to specify that data field for your instance
# of Jira.  Note:  You can retrieve your instance's team ID field name via the following URI where your
# queried user story issue has team set on it; your custom field name describes the
# team value you expect to see:
# https://[your-jira-domain-name]/rest/api/2/issue/[some-issue-name]
#############################################################################
feature.jiraTeamFieldName=customfield_10300

# Defines how to update features per board. If true then only update based on enabled collectorItems otherwise full update
feature.collectorItemOnlyUpdate=true

#Defines the maximum number of features allow per board. If limit is reach collection will not happen for given board
feature.maxNumberOfFeaturesPerBoard=1000

# Set this to true if you use boards as team
feature.jiraBoardAsTeam=true

#Defines the number of hours between each board/team and project data refresh
#feature.refreshTeamAndProjectHours=




this is my property file 

i am able to run collector successfully without error on logs.

i am able to fetch board and rest thing in widgets but not able to get count on the widgets

**Comment by shubhamk0305** [comment]
![image](https://user-images.githubusercontent.com/50317418/75877388-9be95e80-5e3d-11ea-932b-4d96d17ee2a6.png)

but not able to get the data on ui widgets 
![image](https://user-images.githubusercontent.com/50317418/75877359-88d68e80-5e3d-11ea-9339-7dc33e1fb9cf.png)
